name: test coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          make install
      - name: Start inner project linter
        run: |
          make lint
      - name: Start test coverage
        uses: paambaati/codeclimate-action@v2.5.2
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
