name: jest

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          make install
      - name: Start test coverage
        uses: paambaati/codeclimate-action@v2.5.2
        env:
          CC_TEST_REPORTER_ID: 28abab2486d822dd535044da0f2cc85571eabf23189a28ba91dcdd88211fa167
        with:
          coverageCommand: make test-coverage
